version: "3.7"

services:
  go-app:
    container_name: go-app
    image: salaheddine10/go-docker-demo:V1.1
    build: .
    environment:
      DB_NAME: go_api
      DB_USER: postgres
      DB_PASSWORD: salah2000
      DB_HOST: go_db
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: salah2000
      POSTGRES_USER: postgres
      POSTGRES_DB: go_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
