apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: salaheddine10/go-docker-demo:V1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            # Load the environment variables of our go rest api
            - configMapRef:
                name: go-configmap
